services:
  - type: web
    name: ai-sdk
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false  # This will need to be set manually in Render dashboard
      - key: DEFAULT_MODEL
        value: gpt-4o-mini
      - key: MAX_TOKENS
        value: 2000
      - key: TEMPERATURE
        value: 0.7
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_DIR
        value: ./uploads 